list: $/yfktn/backenduserregistration/models/backenduserregistration/columns.yaml
modelClass: Yfktn\BackendUserRegistration\Models\BackendUserRegistration
title: BackendUserRegistration
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'yfktn/backenduserregistration/backenduserregistration/update/:id'
